[book]
authors = ["MingyiZhang"]
language = "en"
multilingual = false
src = "src"
title = "mdbook github page"

[build]
build-dir = "../docs"

[output.html]
theme = "my-theme"
mathjax-support = true
git-repository-url = "https://github.com/MingyiZhang/mdbook-github-page"

[output.html.print]
enable = true